CC = gcc

ex7.3: ex7-3.c
	$(CC) $^

7.3: 7.3.c
	$(CC) $^

ex7.2: ex7-2.c
	$(CC) $^

ex7.1.2: ex7-1.2.c
	$(CC) $^ -o upper
	$(CC) $^ -o lower

ex7.1: ex7-1.c
	$(CC) $^

7.1: 7.1.c
	$(CC) $^

clean:
	rm -f upper lower a.out
