FILE = ex4-8
OBJS = getop.o getch.o stack.o

$(FILE): $(FILE).c $(OBJS)
	gcc $(FILE).c $(OBJS)

ex4-3: ex4-3.c get.c stack.c
	gcc ex4-3.c get.c stack.c

4.3: 4.3.c get.c stack.c
	gcc 4.3.c get.c stack.c

utils: utils.o
	gcc -c utils.c
